package internalframes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.ConnectionProvider;

public class AddFeesInternal extends javax.swing.JInternalFrame {

    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    private myframes.MainFrame1 mf;
    
    public AddFeesInternal(myframes.MainFrame1 mf) {
        this.mf = mf;
        initComponents();
        incorrectID.setVisible(false);
        paymentDateChoose.setDateFormatString("dd-MM-yyyy");
        dueDateChoose.setDateFormatString("dd-MM-yyyy");
    }
    
    
   private String generateFId(){
    Random random = new Random();
        // java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        // Generate a random number between 0 and 100
        String randomChar1 = ""+(char) ('A' + random.nextInt(26)) + 
                             (char) ('A' + random.nextInt(26)) + 
                             (char) ('A' + random.nextInt(26));
//        String randomChar2 = String.valueOf(random.nextInt(26)+'A')+String.valueOf(random.nextInt(26)+'A')+String.valueOf(random.nextInt(26)+'A');
        String randomChar2 = ""+(char) ('A' + random.nextInt(26)) + 
                             (char) ('A' + random.nextInt(26)) + 
                             (char) ('A' + random.nextInt(26));
        int randomNum1 = random.nextInt(101);
        int randomNum2 = random.nextInt(101);
        String id = "FEE" + randomChar1+ randomNum1+randomChar2+randomNum2;
//        System.out.println(id);
//        System.out.println(randomChar1);
//        System.out.println(randomChar2);
        return id;
}
private int getAmount(String mship){
    if(mship.isEmpty()) return 0;
    int amount = 0;
        Connection con = null;
        PreparedStatement pmt = null;
        ResultSet rs = null;
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gms", "root", "root");
            pmt = con.prepareStatement("select charges from membership where mship_id = ?");
            pmt.setString(1, mship);
            rs = pmt.executeQuery();
            int flag = 0;
            if(rs.next())
         {
            flag++;
            amount = rs.getInt("charges");
       }
        con.close();
        pmt.close();
        rs.close();
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddFeesInternal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddFeesInternal.class.getName()).log(Level.SEVERE, null, ex);
        }
        // DB CONNECTION ENDED
    return amount;
}
    
    
private void resetAll(boolean status){
    incorrectID.setVisible(status);
    searchMidTxt.setText("");
    nameTxt.setText("");
    mshipTxt.setText("");
    paymentDateChoose.setDateFormatString("dd-MM-yyyy");
    dueDateChoose.setDateFormatString("dd-MM-yyyy");
    amountTxt.setText("");
    feesIdTxt.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        myButton3 = new buttons.MyButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        amountTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        saveBtn = new buttons.MyButton();
        mshipTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        resetBtn = new buttons.MyButton();
        dueDateChoose = new com.toedter.calendar.JDateChooser();
        searchMidTxt = new javax.swing.JTextField();
        incorrectID = new javax.swing.JLabel();
        searchBtn = new buttons.MyButton();
        paymentDateChoose = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        paidComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        feesIdTxt = new javax.swing.JTextField();

        setBorder(null);
        setFrameIcon(null);

        jPanel1.setBackground(new java.awt.Color(255, 229, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fees");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 330, 90));

        myButton3.setBorder(null);
        myButton3.setText("Prev");
        myButton3.setBorderPainted(false);
        myButton3.setColor(new java.awt.Color(153, 0, 0));
        myButton3.setColorClick(new java.awt.Color(0, 153, 153));
        myButton3.setColorOver(new java.awt.Color(0, 102, 255));
        myButton3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        myButton3.setRadius(35);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, -1));

        jPanel2.setBackground(new java.awt.Color(117, 106, 182));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel11.setText("Search Member id:-");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 18, 257, 45));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Name:-");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 138, 184, 28));

        nameTxt.setEditable(false);
        nameTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        jPanel2.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 182, 332, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Payment Date:-");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 412, 184, 28));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Amount:-");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 320, 184, 28));

        amountTxt.setEditable(false);
        amountTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        amountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTxtActionPerformed(evt);
            }
        });
        jPanel2.add(amountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 360, 332, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Due Date:-");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 234, 184, 28));

        saveBtn.setText("Save");
        saveBtn.setAlignmentY(0.0F);
        saveBtn.setBorderPainted(false);
        saveBtn.setColor(new java.awt.Color(255, 255, 204));
        saveBtn.setColorOver(new java.awt.Color(0, 51, 153));
        saveBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        saveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel2.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 501, 108, 41));

        mshipTxt.setEditable(false);
        mshipTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mshipTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mshipTxtActionPerformed(evt);
            }
        });
        jPanel2.add(mshipTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 272, 332, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Membership:-");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 234, 184, 28));

        resetBtn.setText("Reset");
        resetBtn.setAlignmentY(0.0F);
        resetBtn.setBorderPainted(false);
        resetBtn.setColor(new java.awt.Color(255, 255, 204));
        resetBtn.setColorOver(new java.awt.Color(153, 0, 0));
        resetBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        resetBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel2.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 448, 108, 41));

        dueDateChoose.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(dueDateChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 268, 332, 34));

        searchMidTxt.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        searchMidTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchMidTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMidTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMidTxtMouseEntered(evt);
            }
        });
        searchMidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMidTxtActionPerformed(evt);
            }
        });
        jPanel2.add(searchMidTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 67, 433, 45));

        incorrectID.setBackground(new java.awt.Color(0, 0, 0));
        incorrectID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        incorrectID.setForeground(new java.awt.Color(255, 0, 0));
        incorrectID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        incorrectID.setText("Incorrect id");
        jPanel2.add(incorrectID, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 6, 138, 40));

        searchBtn.setBorder(null);
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchBtn.setText("search");
        searchBtn.setBorderPainted(false);
        searchBtn.setColor(new java.awt.Color(153, 0, 0));
        searchBtn.setColorClick(new java.awt.Color(0, 153, 153));
        searchBtn.setColorOver(new java.awt.Color(0, 102, 255));
        searchBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        searchBtn.setRadius(35);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 67, 113, 49));

        paymentDateChoose.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(paymentDateChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 448, 332, 34));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Paid:-");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 138, 184, 28));

        paidComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paidComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES" }));
        jPanel2.add(paidComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 178, 332, 38));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Fees id:-");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 320, 184, 28));

        feesIdTxt.setEditable(false);
        feesIdTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feesIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesIdTxtActionPerformed(evt);
            }
        });
        jPanel2.add(feesIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 360, 332, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
        mf.switchInternalFrames("Show Fees");
    }//GEN-LAST:event_myButton3ActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void amountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTxtActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if(searchMidTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Member id is empty");
            return;
        }

        String mId = searchMidTxt.getText();
        String mship = mshipTxt.getText();
        String name = nameTxt.getText();
        String amount = amountTxt.getText();

        String paymentDate = sdf.format(paymentDateChoose.getDate());

        String dueDate = sdf.format(dueDateChoose.getDate());
        String paidStatus = (String) paidComboBox.getSelectedItem();
        boolean isPaid = false;
        if(paidStatus.equals("YES")){
            isPaid = true;
        }
        String fId = feesIdTxt.getText();

        try
        {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("INSERT INTO FEES values(?,?,?,?,?,?)");
            ps.setString(1, fId);
            ps.setString(2, mId);
            ps.setString(3, amount);
            ps.setString(4, dueDate);
            ps.setBoolean(5, isPaid);
            ps.setString(6, paymentDate);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully saved");
            con.close();
            ps.close();

            resetAll(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void mshipTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mshipTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mshipTxtActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        resetAll(false);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void searchMidTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMidTxtMouseClicked
        // TODO add your handling code here:
        //      searchTxt.setText("");
    }//GEN-LAST:event_searchMidTxtMouseClicked

    private void searchMidTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMidTxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMidTxtMouseEntered

    private void searchMidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMidTxtActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        if(searchMidTxt.getText().isEmpty())
        {
            incorrectID.setVisible(true);
            return;
        }

        String mship = "";
        String name = "";
        int amount = 0;
        String mid = searchMidTxt.getText();

        Connection con = null;
        PreparedStatement pmt = null;
        ResultSet rs = null;
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gms", "root", "root");
            //  String query = "select * from member where mid = ? ";

            pmt = con.prepareStatement("select m_name, mship_id from member where mid = ? ");
            pmt.setString(1, mid);
            rs = pmt.executeQuery();

            int flag = 0;

            if(rs.next())
            {
                //     table.addRow(new Object[] { resultSet.getString("column_name_1"), resultSet.getString("column_name_2") });}
            flag++;
            name = rs.getString("m_name");
            mship = rs.getString("mship_id");
            // amount = rs.getString("maintenance_date");
        }

        if(flag == 1)
        {
            nameTxt.setText(name);
            mshipTxt.setText(mship);
            amount = getAmount(mship);
            amountTxt.setText(String.valueOf(amount));
            String fid = generateFId();
            feesIdTxt.setText(fid);
        }
        else{
            resetAll(true);
        }
        con.close();
        pmt.close();
        rs.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        // DB CONNECTION ENDED
    }//GEN-LAST:event_searchBtnActionPerformed

    private void feesIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feesIdTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTxt;
    private com.toedter.calendar.JDateChooser dueDateChoose;
    private javax.swing.JTextField feesIdTxt;
    private javax.swing.JLabel incorrectID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mshipTxt;
    private buttons.MyButton myButton3;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox<String> paidComboBox;
    private com.toedter.calendar.JDateChooser paymentDateChoose;
    private buttons.MyButton resetBtn;
    private buttons.MyButton saveBtn;
    private buttons.MyButton searchBtn;
    private javax.swing.JTextField searchMidTxt;
    // End of variables declaration//GEN-END:variables
}
