package internalframes;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import project.ConnectionProvider;
public class MembershipCRUD extends javax.swing.JInternalFrame {

    private myframes.MainFrame1 mf;
    
    public MembershipCRUD(myframes.MainFrame1 mainframe) 
    {
        this.mf = mainframe;
        initComponents();
        refreshTable();
        
        
    }
public void refreshTable(){
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0);
         Connection con = ConnectionProvider.getCon();
        PreparedStatement pmt = null;
        ResultSet rs = null;
        try {
          
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gms", "root", "root");
            String query = "select * from membership";
            pmt = con.prepareStatement(query);
            rs = pmt.executeQuery();
            //table.setModel(DbUtils.resultSetToTableModel(rs));
            while(rs.next())
            {
            //     table.addRow(new Object[] { resultSet.getString("column_name_1"), resultSet.getString("column_name_2") });}
//                String id = rs.getString("mship_id");
//                int duration = rs.getInt("duration");
//                int charges = rs.getInt("charges");
//                String facilities = rs.getString("facilities");
                model.addRow(new Object[]{ rs.getString("mship_id"),rs.getInt("duration"),rs.getInt("charges"),rs.getString("facilities") });
            }
            con.close();
            pmt.close();
            rs.close();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MembershipCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        myButton1 = new buttons.MyButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        addBtn1 = new javax.swing.JButton();
        removeBtn1 = new javax.swing.JButton();

        setBorder(null);
        setFrameIcon(null);

        jPanel1.setBackground(new java.awt.Color(0, 159, 189));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Membership Plan");

        myButton1.setBorder(null);
        myButton1.setText("Prev");
        myButton1.setBorderPainted(false);
        myButton1.setColor(new java.awt.Color(153, 0, 0));
        myButton1.setColorClick(new java.awt.Color(0, 153, 153));
        myButton1.setColorOver(new java.awt.Color(0, 102, 255));
        myButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        myButton1.setRadius(35);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(510, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(74, 36, 157));
        jPanel3.setForeground(new java.awt.Color(0, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        table.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Membership id", "Duration", "Charges", "Facilities"
            }
        ));
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.setGridColor(new java.awt.Color(0, 0, 0));
        table.setName(""); // NOI18N
        table.setRowHeight(30);
        table.setSelectionBackground(new java.awt.Color(102, 102, 102));
        table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowGrid(true);
        table.getTableHeader().setResizingAllowed(false);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 750, 210));

        jPanel2.setBackground(new java.awt.Color(249, 226, 175));
        jPanel2.setForeground(new java.awt.Color(51, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateBtn.setBackground(new java.awt.Color(246, 245, 245));
        updateBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(0, 0, 0));
        updateBtn.setText("Update Membership");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBtnMouseExited(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 230, 60));

        addBtn1.setBackground(new java.awt.Color(246, 245, 245));
        addBtn1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addBtn1.setForeground(new java.awt.Color(0, 0, 0));
        addBtn1.setText("Add new Membership");
        addBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtn1MouseExited(evt);
            }
        });
        addBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(addBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 230, 60));

        removeBtn1.setBackground(new java.awt.Color(246, 245, 245));
        removeBtn1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        removeBtn1.setForeground(new java.awt.Color(0, 0, 0));
        removeBtn1.setText("Remove Membership");
        removeBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeBtn1MouseExited(evt);
            }
        });
        removeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(removeBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1070, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
        mf.switchInternalFrames("Select Entities");
    }//GEN-LAST:event_myButton1ActionPerformed

    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        // TODO add your handling code here:
        updateBtn.setBackground(new Color(255,255,255));
        updateBtn.setForeground(new Color(00,00,00));

    }//GEN-LAST:event_updateBtnMouseEntered

    private void updateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseExited
        // TODO add your handling code here:
        updateBtn.setBackground(new Color(204,102,0));
        updateBtn.setForeground(new Color(00,00,00));

    }//GEN-LAST:event_updateBtnMouseExited

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        mf.switchInternalFrames("Update Membership");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtn1MouseEntered
        // TODO add your handling code here:
        addBtn1.setBackground(new Color(255,255,255));
        addBtn1.setForeground(new Color(00,00,00));

    }//GEN-LAST:event_addBtn1MouseEntered

    private void addBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtn1MouseExited
        // TODO add your handling code here:
        addBtn1.setBackground(new Color(204,102,0));
        addBtn1.setForeground(new Color(00,00,00));

    }//GEN-LAST:event_addBtn1MouseExited

    private void addBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn1ActionPerformed
        mf.switchInternalFrames("Add Membership");
    }//GEN-LAST:event_addBtn1ActionPerformed

    private void removeBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBtn1MouseEntered
        // TODO add your handling code here:
        removeBtn1.setBackground(new Color(255,255,255));
        removeBtn1.setForeground(new Color(00,00,00));

    }//GEN-LAST:event_removeBtn1MouseEntered

    private void removeBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBtn1MouseExited
        // TODO add your handling code here:
        removeBtn1.setBackground(new Color(204,102,0));
        removeBtn1.setForeground(new Color(00,00,00));

    }//GEN-LAST:event_removeBtn1MouseExited

    private void removeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtn1ActionPerformed
        mf.switchInternalFrames("Remove Membership");
    }//GEN-LAST:event_removeBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private buttons.MyButton myButton1;
    private javax.swing.JButton removeBtn1;
    private javax.swing.JTable table;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
