/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package internalframes;

import java.awt.Color;
import myframes.MainFrame1;


public class SelectEntities extends javax.swing.JInternalFrame {
private MainFrame1 mf;
    public SelectEntities(MainFrame1 mainframe) {
        this.mf = mainframe;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        memberBtn = new javax.swing.JButton();
        mshipBtn = new javax.swing.JButton();
        trainerBtn = new javax.swing.JButton();
        rawBtn = new javax.swing.JButton();
        equipmentBtn = new javax.swing.JButton();
        feesBtn = new javax.swing.JButton();

        setBorder(null);
        setFrameIcon(null);

        jPanel1.setBackground(new java.awt.Color(234, 144, 108));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(179, 19, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 12, 270, 80));

        jPanel2.setBackground(new java.awt.Color(238, 226, 222));

        memberBtn.setBackground(new java.awt.Color(0, 0, 0));
        memberBtn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        memberBtn.setForeground(new java.awt.Color(255, 255, 255));
        memberBtn.setText("Member");
        memberBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), null));
        memberBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                memberBtnMouseDragged(evt);
            }
        });
        memberBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                memberBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                memberBtnMouseExited(evt);
            }
        });
        memberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberBtnActionPerformed(evt);
            }
        });

        mshipBtn.setBackground(new java.awt.Color(0, 0, 0));
        mshipBtn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        mshipBtn.setForeground(new java.awt.Color(255, 255, 255));
        mshipBtn.setText("Membership Plans");
        mshipBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), null));
        mshipBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mshipBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mshipBtnMouseExited(evt);
            }
        });
        mshipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mshipBtnActionPerformed(evt);
            }
        });

        trainerBtn.setBackground(new java.awt.Color(0, 0, 0));
        trainerBtn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        trainerBtn.setForeground(new java.awt.Color(255, 255, 255));
        trainerBtn.setText("Trainer");
        trainerBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), null));
        trainerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trainerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trainerBtnMouseExited(evt);
            }
        });
        trainerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainerBtnActionPerformed(evt);
            }
        });

        rawBtn.setBackground(new java.awt.Color(0, 0, 0));
        rawBtn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        rawBtn.setForeground(new java.awt.Color(255, 255, 255));
        rawBtn.setText("Raw Materials");
        rawBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), null));
        rawBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rawBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rawBtnMouseExited(evt);
            }
        });
        rawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawBtnActionPerformed(evt);
            }
        });

        equipmentBtn.setBackground(new java.awt.Color(0, 0, 0));
        equipmentBtn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        equipmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        equipmentBtn.setText("Equipment");
        equipmentBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), null));
        equipmentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equipmentBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equipmentBtnMouseExited(evt);
            }
        });
        equipmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentBtnActionPerformed(evt);
            }
        });

        feesBtn.setBackground(new java.awt.Color(0, 0, 0));
        feesBtn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        feesBtn.setForeground(new java.awt.Color(255, 255, 255));
        feesBtn.setText("Fees");
        feesBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), null));
        feesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                feesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                feesBtnMouseExited(evt);
            }
        });
        feesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rawBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(trainerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memberBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mshipBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(feesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(equipmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mshipBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trainerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(feesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rawBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(equipmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void memberBtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberBtnMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_memberBtnMouseDragged

    private void memberBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberBtnMouseEntered
        // TODO add your handling code here:
        memberBtn.setBackground(new Color(255,255,255));
        memberBtn.setForeground(new Color(00,00,00));
    }//GEN-LAST:event_memberBtnMouseEntered

    private void memberBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberBtnMouseExited
        // TODO add your handling code here:
        memberBtn.setBackground(new Color(00,00,00));
        memberBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_memberBtnMouseExited

    private void memberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberBtnActionPerformed
        mf.switchInternalFrames("Show Members");
    }//GEN-LAST:event_memberBtnActionPerformed

    private void mshipBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mshipBtnMouseEntered
        // TODO add your handling code here:
        mshipBtn.setBackground(new Color(255,255,255));
        mshipBtn.setForeground(new Color(0,0,0));

    }//GEN-LAST:event_mshipBtnMouseEntered

    private void mshipBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mshipBtnMouseExited
        // TODO add your handling code here:  mshipBtn
        mshipBtn.setBackground(new Color(0,0,0));
        mshipBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_mshipBtnMouseExited

    private void mshipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mshipBtnActionPerformed
        // TODO add your handling code here:
        mf.switchInternalFrames("Show Membership");
    }//GEN-LAST:event_mshipBtnActionPerformed

    private void trainerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainerBtnMouseEntered
        // TODO add your handling code here:
        trainerBtn.setBackground(new Color(255,255,255));
        trainerBtn.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_trainerBtnMouseEntered

    private void trainerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainerBtnMouseExited
        // TODO add your handling code here:
        trainerBtn.setBackground(new Color(0,0,0));
        trainerBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_trainerBtnMouseExited

    private void trainerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainerBtnActionPerformed
        mf.switchInternalFrames("Show Trainers");
    }//GEN-LAST:event_trainerBtnActionPerformed

    private void rawBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawBtnMouseEntered
        // TODO add your handling code here:
        rawBtn.setBackground(new Color(255,255,255));
        rawBtn.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_rawBtnMouseEntered

    private void rawBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawBtnMouseExited
        // TODO add your handling code here:
        rawBtn.setBackground(new Color(0,0,0));
        rawBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_rawBtnMouseExited

    private void equipmentBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentBtnMouseEntered
        // TODO add your handling code here:
        equipmentBtn.setBackground(new Color(255,255,255));
        equipmentBtn.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_equipmentBtnMouseEntered

    private void equipmentBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentBtnMouseExited
        // TODO add your handling code here:
        equipmentBtn.setBackground(new Color(0,0,0));
        equipmentBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_equipmentBtnMouseExited

    private void equipmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentBtnActionPerformed
        // TODO add your handling code here:
        mf.switchInternalFrames("Show Equipments");
    }//GEN-LAST:event_equipmentBtnActionPerformed

    private void feesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feesBtnMouseEntered
        // TODO add your handling code here:
        feesBtn.setBackground(new Color(255,255,255));
        feesBtn.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_feesBtnMouseEntered

    private void feesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feesBtnMouseExited
        // TODO add your handling code here:
        feesBtn.setBackground(new Color(0,0,0));
        feesBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_feesBtnMouseExited

    private void feesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesBtnActionPerformed
        mf.switchInternalFrames("Show Fees");
    }//GEN-LAST:event_feesBtnActionPerformed

    private void rawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawBtnActionPerformed
        // TODO add your handling code here:
        mf.switchInternalFrames("Show Raw Materials");
       
    }//GEN-LAST:event_rawBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton equipmentBtn;
    private javax.swing.JButton feesBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton memberBtn;
    private javax.swing.JButton mshipBtn;
    private javax.swing.JButton rawBtn;
    private javax.swing.JButton trainerBtn;
    // End of variables declaration//GEN-END:variables
}
